### ISSUE TITLE
ione ui login failed

### ISSUE THREAD

**Issue by chicco64** [ione-cloud/ione#90]
Hi !
I Just use my oneadmin credentials (psw and token) at ione-admin, but don't work.
<img width="770" alt="er2" src="https://user-images.githubusercontent.com/59960414/111352658-554b5880-867c-11eb-806f-ba4b84f16d34.PNG">

**Comment by slntopp** [comment]
Could you please share/check which endpoint is being used for request, which fails?
Are your DNS records set up, so ione-api.yourdomain is resolvable?

**Comment by chicco64** [comment]
Hi !
"ione-api.mydomain" is resolvable...(DNS is update)
how can i check you which one endpoint is used for request ?
thanks

**Comment by slntopp** [comment]
Open DevTools in your browser, navigate to Network tab and try login again. You'll see failed request there, it's full URL, response code and response message. Please share it here

**Comment by slntopp** [comment]
You can also upgrade UI from v1.0.2 branch, just added debug message there

**Comment by chicco64** [comment]
ok ready, but don' t work yet
<img width="1043" alt="er4" src="https://user-images.githubusercontent.com/59960414/111471393-c47a8880-8720-11eb-97f2-22f974a38f08.PNG">

**Comment by slntopp** [comment]
1. Navigate to `/usr/lib/one/ione/ui`
2. Run `VUE_APP_IONE_API_BASE_URL=https://ione-api.yourdomain npm run build`

**Comment by chicco64** [comment]
Now the endpoint is correct, but the login don't work

<img width="736" alt="er6" src="https://user-images.githubusercontent.com/59960414/111476005-9b102b80-8725-11eb-8196-f01c85a59028.PNG">

**Comment by slntopp** [comment]
What is in response of `one.u.to_hash` request?

**Comment by chicco64** [comment]
<img width="1059" alt="er7" src="https://user-images.githubusercontent.com/59960414/111477471-0eff0380-8727-11eb-8b6f-871065ec6d51.PNG">

**Comment by slntopp** [comment]
Could you test this request from console?
1. Right-click on POST request
2. Copy as: cURL
3. Add -v flag and try in terminal

**Comment by chicco64** [comment]
I don't know....
[curl.txt](https://github.com/ione-cloud/ione/files/6156951/curl.txt)

**Comment by slntopp** [comment]
Got it. Currently you have self signed certificate generated by installer. Replace it with proper cert, for example Let'sEncrypt.
Certificate, key and pem are under `/etc/one/ssl/`

**Comment by chicco64** [comment]
Hi ! Sorry but don't work yet.....

---------------------------------------------------------
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=cloud.mydomain.xyz
*  start date: Mar 17 19:36:26 2021 GMT
*  expire date: Jun 15 19:36:26 2021 GMT
*  subjectAltName: host "ione-api.mydomain.xyz" matched cert's "ione-api.mydomain.xyz"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> POST /one.u.to_hash! HTTP/1.1
> Host: ione-api.mydomain.xyz
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
> Accept: application/json, text/plain, */*
> Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
> Content-Type: application/json;charset=utf-8
> Authorization: Basic b25lYWRtaW46RmFudGR2ZDY0Zm0yMDIxQA==
> Origin: https://ione-admin.mydomain.xyz
> DNT: 1
> Connection: keep-alive
> Referer: https://ione-admin.mydomain.xyz/
> Content-Length: 0
>
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.14.1
< Date: Wed, 17 Mar 2021 21:14:51 GMT
< Content-Type: text/html
< Content-Length: 173
< Connection: keep-alive
* HTTP error before end of send, stop sending
<
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
* Closing connection 0

**Comment by slntopp** [comment]
If you've ensured `ione.service` is up and running, then you may need to check if IONe is available on localhost
So first try cURL request above replacing `https://ione-api.yourdomain` with `http://localhost:8009` / `http://127.0.0.1:8009`.
If that won't work either, you should check your internal networking configuration.

IONe server binds to localhost. NGINX configured to proxy to `127.0.0.1` by default. I've faced similar issue once as server was configured to use IPv6 and `::1` as `localhost`

**Comment by chicco64** [comment]
Hi ! sorry for delay ! This is the result:
<img width="905" alt="C1" src="https://user-images.githubusercontent.com/59960414/112819205-3eddcd80-907c-11eb-8482-980f9d2f4f64.PNG">
i believe it is not nginx problem but ion service not starting up regularly
please let me know what i can still do, thanks

**Comment by slntopp** [comment]
But what about rest of cURLs, as `curl http://localhost:8009`?

**Comment by chicco64** [comment]
# curl http://localhost:8009
No Credentials given[root@opennebula-frontend ~]#

<img width="574" alt="C3" src="https://user-images.githubusercontent.com/59960414/112824895-04c3fa00-9083-11eb-8a34-82bd4998762e.PNG">

**Comment by slntopp** [comment]
Alright, I see
Replace 127.0.0.1 with localhost everywhere in `/etc/nginx/conf.d/yourdomain.conf`

**Comment by chicco64** [comment]
Now works ! many thanks
<img width="1258" alt="C4" src="https://user-images.githubusercontent.com/59960414/112841232-27acd900-9098-11eb-90c8-290bd8772a56.PNG">

**Comment by slntopp** [comment]
Great, thanks for contributing
